version: '3.8'

services:
  goodwe-exporter:
    container_name: goodwe-exporter
    build: .
    ports:
      - 8787:8787
    command:
      - "--port=8787"
      - "--interval=30"
      - "--inverter=192.168.1.10"
      - "--energy-price=0.15"
      - "--PVpower=5.67"
      - "--scrape-spot-price=False"
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    external: false
    driver: bridge

