version: '3.8'

services:
  goodwe-exporter:
    container_name: goodwe-exporter-test
    image: goodwe-exporter:1.4.1
    #    build: .
    ports:
      - 12345:8787
    command:
      - "--port=8787"
      - "--interval=20"
      - "--inverter=192.168.2.35"
      - "--energy-price=0.15"
      - "--PVpower=5670"
      - "--scrape-spot-price=True"
      - "--spot-scrape-interval=10"
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    external: false
    driver: bridge

